name = "spacefaring-news-ingest"
main = "ingest/worker.js"
compatibility_date = "2026-06-10"

[triggers]
crons = ["*/30 * * * *"]

[[d1_databases]]
binding = "NEWS_DB"
database_name = "spacefaring-news"
database_id = "81b107b9-e3f0-47f4-a976-23a26b10a0c6"
