import type { FeedSource } from "./types";

export const NEWS_SOURCES: FeedSource[] = [
  {
    id: "nasa-news-releases",
    title: "NASA News Releases",
    url: "https://www.nasa.gov/news-release/feed/",
    homepage: "https://www.nasa.gov/news-release/",
    category: "agency",
    language: "en",
    region: "us",
    cadenceMinutes: 30,
  },
  {
    id: "nasa-recently-published",
    title: "NASA Recently Published",
    url: "https://www.nasa.gov/feed/",
    homepage: "https://www.nasa.gov/news/",
    category: "agency",
    language: "en",
    region: "us",
    cadenceMinutes: 30,
  },
  {
    id: "nasa-artemis",
    title: "NASA Artemis",
    url: "https://www.nasa.gov/missions/artemis/feed/",
    homepage: "https://www.nasa.gov/missions/artemis/",
    category: "agency",
    language: "en",
    region: "us",
    cadenceMinutes: 30,
  },
  {
    id: "nasa-space-station",
    title: "NASA Space Station",
    url: "https://www.nasa.gov/missions/station/feed/",
    homepage: "https://www.nasa.gov/missions/station/",
    category: "agency",
    language: "en",
    region: "us",
    cadenceMinutes: 30,
  },
  {
    id: "nasa-earth",
    title: "NASA Earth",
    url: "https://www.nasa.gov/earth/feed/",
    homepage: "https://www.nasa.gov/earth/",
    category: "science",
    language: "en",
    region: "us",
    cadenceMinutes: 60,
  },
  {
    id: "nasa-technology",
    title: "NASA Technology",
    url: "https://www.nasa.gov/technology/feed/",
    homepage: "https://www.nasa.gov/technology/",
    category: "science",
    language: "en",
    region: "us",
    cadenceMinutes: 60,
  },
  {
    id: "nasa-aeronautics",
    title: "NASA Aeronautics",
    url: "https://www.nasa.gov/aeronautics/feed/",
    homepage: "https://www.nasa.gov/aeronautics/",
    category: "science",
    language: "en",
    region: "us",
    cadenceMinutes: 60,
  },
  {
    id: "nasa-jpl",
    title: "NASA Jet Propulsion Laboratory",
    url: "https://www.nasa.gov/centers-and-facilities/jpl/feed/",
    homepage: "https://www.nasa.gov/centers-and-facilities/jpl/",
    category: "science",
    language: "en",
    region: "us",
    cadenceMinutes: 60,
  },
  {
    id: "nasa-kennedy",
    title: "NASA Kennedy Space Center",
    url: "https://www.nasa.gov/centers-and-facilities/kennedy/feed/",
    homepage: "https://www.nasa.gov/centers-and-facilities/kennedy/",
    category: "launch",
    language: "en",
    region: "us",
    cadenceMinutes: 60,
  },
  {
    id: "esa-top-news",
    title: "ESA Top News",
    url: "https://www.esa.int/rssfeed/TopNews",
    homepage: "https://www.esa.int/",
    category: "agency",
    language: "en",
    region: "europe",
    cadenceMinutes: 30,
  },
  {
    id: "spacewatch-global",
    title: "SpaceWatch.Global",
    url: "https://spacewatch.global/feed/",
    homepage: "https://spacewatch.global/",
    category: "industry",
    language: "en",
    region: "global",
    cadenceMinutes: 60,
  },
  {
    id: "space-in-africa",
    title: "Space in Africa",
    url: "https://spaceinafrica.com/feed/",
    homepage: "https://spaceinafrica.com/",
    category: "industry",
    language: "en",
    region: "africa",
    cadenceMinutes: 60,
  },
  {
    id: "latam-satelital",
    title: "Latam Satelital",
    url: "https://latamsatelital.com/feed/",
    homepage: "https://latamsatelital.com/",
    category: "satellite",
    language: "es",
    region: "latam",
    cadenceMinutes: 60,
  },
  {
    id: "geospatial-world",
    title: "Geospatial World",
    url: "https://www.geospatialworld.net/feed/",
    homepage: "https://www.geospatialworld.net/",
    category: "satellite",
    language: "en",
    region: "global",
    cadenceMinutes: 60,
  },
  {
    id: "india-today-science",
    title: "India Today Science",
    url: "https://www.indiatoday.in/rss/1206578",
    homepage: "https://www.indiatoday.in/science",
    category: "science",
    language: "en",
    region: "india",
    cadenceMinutes: 60,
  },
  {
    id: "the-hindu-science",
    title: "The Hindu Science",
    url: "https://www.thehindu.com/sci-tech/science/feeder/default.rss",
    homepage: "https://www.thehindu.com/sci-tech/science/",
    category: "science",
    language: "en",
    region: "india",
    cadenceMinutes: 60,
  },
  {
    id: "times-of-india-science",
    title: "Times of India Science",
    url: "https://timesofindia.indiatimes.com/rssfeeds/5880659.cms",
    homepage: "https://timesofindia.indiatimes.com/science",
    category: "science",
    language: "en",
    region: "india",
    cadenceMinutes: 60,
  },
  {
    id: "agnikul-cosmos",
    title: "Agnikul Cosmos",
    url: "https://agnikul.in/feed/",
    homepage: "https://agnikul.in/",
    category: "commercial",
    language: "en",
    region: "india",
    cadenceMinutes: 60,
  },
  {
    id: "china-daily-scitech",
    title: "China Daily Sci-Tech",
    url: "https://www.chinadaily.com.cn/rss/china_rss.xml",
    homepage: "https://www.chinadaily.com.cn/china/scitech",
    category: "science",
    language: "en",
    region: "china",
    cadenceMinutes: 60,
  },
  {
    id: "china-daily-world",
    title: "China Daily World",
    url: "https://www.chinadaily.com.cn/rss/world_rss.xml",
    homepage: "https://www.chinadaily.com.cn/world",
    category: "industry",
    language: "en",
    region: "china",
    cadenceMinutes: 60,
  },
  {
    id: "space-news-china",
    title: "SpaceNews China",
    url: "https://spacenews.com/tag/china/feed/",
    homepage: "https://spacenews.com/tag/china/",
    category: "industry",
    language: "en",
    region: "china",
    cadenceMinutes: 60,
  },
  {
    id: "space-news-india",
    title: "SpaceNews India",
    url: "https://spacenews.com/tag/india/feed/",
    homepage: "https://spacenews.com/tag/india/",
    category: "industry",
    language: "en",
    region: "india",
    cadenceMinutes: 60,
  },
  {
    id: "space-news-uae",
    title: "SpaceNews UAE",
    url: "https://spacenews.com/tag/uae/feed/",
    homepage: "https://spacenews.com/tag/uae/",
    category: "industry",
    language: "en",
    region: "mena",
    cadenceMinutes: 60,
  },
  {
    id: "mbrsc",
    title: "Mohammed Bin Rashid Space Centre",
    url: "https://www.mbrsc.ae/feed/",
    homepage: "https://www.mbrsc.ae/",
    category: "agency",
    language: "en",
    region: "mena",
    cadenceMinutes: 60,
  },
  {
    id: "arab-news-space",
    title: "Arab News Space",
    url: "https://www.arabnews.com/taxonomy/term/1006/feed",
    homepage: "https://www.arabnews.com/space",
    category: "industry",
    language: "en",
    region: "mena",
    cadenceMinutes: 60,
  },
  {
    id: "satellitepro-me",
    title: "SatellitePro Middle East",
    url: "https://www.satelliteprome.com/feed/",
    homepage: "https://www.satelliteprome.com/",
    category: "satellite",
    language: "en",
    region: "mena",
    cadenceMinutes: 60,
  },
  {
    id: "tass-space",
    title: "TASS Space",
    url: "https://tass.com/rss/v2.xml?sections=space",
    homepage: "https://tass.com/space",
    category: "agency",
    language: "en",
    region: "russia",
    cadenceMinutes: 60,
  },
  {
    id: "eureka-daniel-marin",
    title: "Eureka / Daniel Marin",
    url: "https://danielmarin.naukas.com/feed/",
    homepage: "https://danielmarin.naukas.com/",
    category: "science",
    language: "es",
    region: "spain",
    cadenceMinutes: 60,
  },
  {
    id: "actualidad-aeroespacial",
    title: "Actualidad Aeroespacial",
    url: "https://actualidadaeroespacial.com/feed/",
    homepage: "https://actualidadaeroespacial.com/",
    category: "industry",
    language: "es",
    region: "spain",
    cadenceMinutes: 60,
  },
  {
    id: "infoespacial",
    title: "InfoEspacial",
    url: "https://www.infoespacial.com/rss/portada.xml",
    homepage: "https://www.infoespacial.com/",
    category: "industry",
    language: "es",
    region: "spain",
    cadenceMinutes: 60,
  },
  {
    id: "futura-sciences-espace",
    title: "Futura Sciences Espace",
    url: "https://www.futura-sciences.com/rss/espace/actualites.xml",
    homepage: "https://www.futura-sciences.com/sciences/espace/",
    category: "science",
    language: "fr",
    region: "france",
    cadenceMinutes: 60,
  },
  {
    id: "raumfahrer-net",
    title: "Raumfahrer.net",
    url: "https://www.raumfahrer.net/feed/",
    homepage: "https://www.raumfahrer.net/",
    category: "industry",
    language: "de",
    region: "germany",
    cadenceMinutes: 60,
  },
  {
    id: "sorae",
    title: "Sorae",
    url: "https://sorae.info/feed",
    homepage: "https://sorae.info/",
    category: "science",
    language: "ja",
    region: "japan",
    cadenceMinutes: 60,
  },
  {
    id: "sansa",
    title: "South African National Space Agency",
    url: "https://www.sansa.org.za/feed/",
    homepage: "https://www.sansa.org.za/",
    category: "agency",
    language: "en",
    region: "africa",
    cadenceMinutes: 60,
  },
  {
    id: "olhar-digital-space",
    title: "Olhar Digital Ciencia e Espaco",
    url: "https://olhardigital.com.br/editorias/ciencia-e-espaco/feed/",
    homepage: "https://olhardigital.com.br/editorias/ciencia-e-espaco/",
    category: "science",
    language: "pt",
    region: "brazil",
    cadenceMinutes: 60,
  },
  {
    id: "kosmonauta-net",
    title: "Kosmonauta.net",
    url: "https://kosmonauta.net/feed/",
    homepage: "https://kosmonauta.net/",
    category: "industry",
    language: "pl",
    region: "poland",
    cadenceMinutes: 60,
  },
  {
    id: "polsa",
    title: "Polish Space Agency",
    url: "https://polsa.gov.pl/feed/",
    homepage: "https://polsa.gov.pl/",
    category: "agency",
    language: "pl",
    region: "poland",
    cadenceMinutes: 60,
  },
  {
    id: "israel-space-agency",
    title: "Israel Space Agency",
    url: "https://www.space.gov.il/en/rss.xml",
    homepage: "https://www.space.gov.il/en",
    category: "agency",
    language: "en",
    region: "israel",
    cadenceMinutes: 60,
  },
  {
    id: "space-news",
    title: "SpaceNews",
    url: "https://spacenews.com/feed/",
    homepage: "https://spacenews.com/",
    category: "industry",
    language: "en",
    region: "us",
    cadenceMinutes: 30,
  },
  {
    id: "spaceflight-now",
    title: "Spaceflight Now",
    url: "https://spaceflightnow.com/feed/",
    homepage: "https://spaceflightnow.com/",
    category: "launch",
    language: "en",
    region: "us",
    cadenceMinutes: 30,
  },
  {
    id: "space-dot-com",
    title: "Space.com",
    url: "https://www.space.com/feeds.xml",
    homepage: "https://www.space.com/",
    category: "industry",
    language: "en",
    region: "us",
    cadenceMinutes: 30,
  },
  {
    id: "universe-today",
    title: "Universe Today",
    url: "https://www.universetoday.com/feed/",
    homepage: "https://www.universetoday.com/",
    category: "astronomy",
    language: "en",
    region: "global",
    cadenceMinutes: 60,
  },
  {
    id: "planetary-society",
    title: "The Planetary Society",
    url: "https://www.planetary.org/rss/articles",
    homepage: "https://www.planetary.org/articles",
    category: "science",
    language: "en",
    region: "us",
    cadenceMinutes: 60,
  },
  {
    id: "space-policy-online",
    title: "SpacePolicyOnline",
    url: "https://spacepolicyonline.com/feed/",
    homepage: "https://spacepolicyonline.com/",
    category: "policy",
    language: "en",
    region: "us",
    cadenceMinutes: 30,
  },
  {
    id: "nasa-watch",
    title: "NASA Watch",
    url: "https://nasawatch.com/feed/",
    homepage: "https://nasawatch.com/",
    category: "policy",
    language: "en",
    region: "us",
    cadenceMinutes: 60,
  },
  {
    id: "phys-org-space",
    title: "Phys.org Space",
    url: "https://phys.org/rss-feed/space-news/",
    homepage: "https://phys.org/space-news/",
    category: "science",
    language: "en",
    region: "global",
    cadenceMinutes: 60,
  },
  {
    id: "science-daily-space-time",
    title: "ScienceDaily Space & Time",
    url: "https://www.sciencedaily.com/rss/space_time.xml",
    homepage: "https://www.sciencedaily.com/news/space_time/",
    category: "science",
    language: "en",
    region: "global",
    cadenceMinutes: 60,
  },
  {
    id: "earthsky",
    title: "EarthSky",
    url: "https://earthsky.org/feed/",
    homepage: "https://earthsky.org/",
    category: "astronomy",
    language: "en",
    region: "us",
    cadenceMinutes: 60,
  },
  {
    id: "astronomy-magazine",
    title: "Astronomy Magazine",
    url: "https://www.astronomy.com/feed/",
    homepage: "https://www.astronomy.com/",
    category: "astronomy",
    language: "en",
    region: "us",
    cadenceMinutes: 60,
  },
  {
    id: "astronomy-now",
    title: "Astronomy Now",
    url: "https://astronomynow.com/feed/",
    homepage: "https://astronomynow.com/",
    category: "astronomy",
    language: "en",
    region: "global",
    cadenceMinutes: 60,
  },
  {
    id: "spaceq",
    title: "SpaceQ",
    url: "https://spaceq.ca/feed/",
    homepage: "https://spaceq.ca/",
    category: "industry",
    language: "en",
    region: "canada",
    cadenceMinutes: 60,
  },
  {
    id: "space-explored",
    title: "Space Explored",
    url: "https://spaceexplored.com/feed/",
    homepage: "https://spaceexplored.com/",
    category: "commercial",
    language: "en",
    region: "us",
    cadenceMinutes: 60,
  },
  {
    id: "satnews",
    title: "SatNews",
    url: "https://news.satnews.com/feed/",
    homepage: "https://news.satnews.com/",
    category: "satellite",
    language: "en",
    region: "us",
    cadenceMinutes: 60,
  },
  {
    id: "payload-space",
    title: "Payload Space",
    url: "https://payloadspace.com/feed/",
    homepage: "https://payloadspace.com/",
    category: "commercial",
    language: "en",
    region: "us",
    cadenceMinutes: 30,
  },
  {
    id: "european-spaceflight",
    title: "European Spaceflight",
    url: "https://europeanspaceflight.com/feed/",
    homepage: "https://europeanspaceflight.com/",
    category: "launch",
    language: "en",
    region: "europe",
    cadenceMinutes: 60,
  },
  {
    id: "rocket-lab",
    title: "Rocket Lab",
    url: "https://www.rocketlabusa.com/updates/rss/",
    homepage: "https://www.rocketlabusa.com/updates/",
    category: "commercial",
    language: "en",
    region: "new-zealand",
    cadenceMinutes: 60,
  },
  {
    id: "firefly-aerospace",
    title: "Firefly Aerospace",
    url: "https://fireflyspace.com/feed/",
    homepage: "https://fireflyspace.com/news/",
    category: "commercial",
    language: "en",
    region: "us",
    cadenceMinutes: 60,
  },
  {
    id: "us-space-force",
    title: "U.S. Space Force",
    url: "https://www.spaceforce.mil/DesktopModules/ArticleCS/RSS.ashx?ContentType=1&Site=1060&Category=9976&max=20",
    homepage: "https://www.spaceforce.mil/News/",
    category: "defense",
    language: "en",
    region: "us",
    cadenceMinutes: 60,
  },
  {
    id: "vandenberg-launches",
    title: "Vandenberg Space Force Base Launches",
    url: "https://www.vandenberg.spaceforce.mil/DesktopModules/ArticleCS/RSS.ashx?ContentType=1&Site=1028&Category=12341&max=20",
    homepage: "https://www.vandenberg.spaceforce.mil/News/Launches/",
    category: "launch",
    language: "en",
    region: "us",
    cadenceMinutes: 60,
  },
  {
    id: "noaa-space-weather",
    title: "NOAA Space Weather Prediction Center",
    url: "https://www.swpc.noaa.gov/rss.xml",
    homepage: "https://www.swpc.noaa.gov/",
    category: "science",
    language: "en",
    region: "us",
    cadenceMinutes: 30,
  },
  {
    id: "cnes",
    title: "CNES",
    url: "https://cnes.fr/en/rss.xml",
    homepage: "https://cnes.fr/en",
    category: "agency",
    language: "en",
    region: "france",
    cadenceMinutes: 60,
  },
  {
    id: "uk-space-agency",
    title: "UK Space Agency",
    url: "https://www.gov.uk/search/news-and-communications.atom?organisations%5B%5D=uk-space-agency",
    homepage: "https://www.gov.uk/government/organisations/uk-space-agency",
    category: "agency",
    language: "en",
    region: "uk",
    cadenceMinutes: 60,
  },
  {
    id: "space-foundation",
    title: "Space Foundation",
    url: "https://www.spacefoundation.org/feed/",
    homepage: "https://www.spacefoundation.org/",
    category: "industry",
    language: "en",
    region: "us",
    cadenceMinutes: 60,
  },
  {
    id: "defense-news-space",
    title: "Defense News Space",
    url: "https://www.defensenews.com/arc/outboundfeeds/rss/category/space/?outputType=xml",
    homepage: "https://www.defensenews.com/space/",
    category: "defense",
    language: "en",
    region: "us",
    cadenceMinutes: 60,
  },
  {
    id: "c4isrnet-space",
    title: "C4ISRNET Space",
    url: "https://www.c4isrnet.com/arc/outboundfeeds/rss/category/battlefield-tech/space/?outputType=xml",
    homepage: "https://www.c4isrnet.com/battlefield-tech/space/",
    category: "defense",
    language: "en",
    region: "us",
    cadenceMinutes: 60,
  },
  {
    id: "aviation-week",
    title: "Aviation Week",
    url: "https://aviationweek.com/rss.xml",
    homepage: "https://aviationweek.com/space",
    category: "industry",
    language: "en",
    region: "us",
    cadenceMinutes: 60,
  },
  {
    id: "space-daily",
    title: "Space Daily",
    url: "https://www.spacedaily.com/spacedaily.xml",
    homepage: "https://www.spacedaily.com/",
    category: "industry",
    language: "en",
    region: "global",
    cadenceMinutes: 60,
  },
  {
    id: "mars-daily",
    title: "Mars Daily",
    url: "https://www.marsdaily.com/marsdaily.xml",
    homepage: "https://www.marsdaily.com/",
    category: "science",
    language: "en",
    region: "global",
    cadenceMinutes: 60,
  },
  {
    id: "space-ref",
    title: "SpaceRef",
    url: "https://spaceref.com/feed/",
    homepage: "https://spaceref.com/",
    category: "industry",
    language: "en",
    region: "us",
    cadenceMinutes: 60,
  },
];

export const NEWS_SOURCE_COUNT = NEWS_SOURCES.length;
