import type { FeedSource } from "./types";

export const NEWS_SOURCES: FeedSource[] = [
  {
    id: "nasa-news-releases",
    title: "NASA News Releases",
    url: "https://www.nasa.gov/news-release/feed/",
    homepage: "https://www.nasa.gov/news-release/",
    category: "agency",
    cadenceMinutes: 30,
  },
  {
    id: "nasa-recently-published",
    title: "NASA Recently Published",
    url: "https://www.nasa.gov/feed/",
    homepage: "https://www.nasa.gov/news/",
    category: "agency",
    cadenceMinutes: 30,
  },
  {
    id: "nasa-artemis",
    title: "NASA Artemis",
    url: "https://www.nasa.gov/missions/artemis/feed/",
    homepage: "https://www.nasa.gov/missions/artemis/",
    category: "agency",
    cadenceMinutes: 30,
  },
  {
    id: "nasa-space-station",
    title: "NASA Space Station",
    url: "https://www.nasa.gov/missions/station/feed/",
    homepage: "https://www.nasa.gov/missions/station/",
    category: "agency",
    cadenceMinutes: 30,
  },
  {
    id: "nasa-earth",
    title: "NASA Earth",
    url: "https://www.nasa.gov/earth/feed/",
    homepage: "https://www.nasa.gov/earth/",
    category: "science",
    cadenceMinutes: 60,
  },
  {
    id: "nasa-technology",
    title: "NASA Technology",
    url: "https://www.nasa.gov/technology/feed/",
    homepage: "https://www.nasa.gov/technology/",
    category: "science",
    cadenceMinutes: 60,
  },
  {
    id: "nasa-aeronautics",
    title: "NASA Aeronautics",
    url: "https://www.nasa.gov/aeronautics/feed/",
    homepage: "https://www.nasa.gov/aeronautics/",
    category: "science",
    cadenceMinutes: 60,
  },
  {
    id: "nasa-jpl",
    title: "NASA Jet Propulsion Laboratory",
    url: "https://www.nasa.gov/centers-and-facilities/jpl/feed/",
    homepage: "https://www.nasa.gov/centers-and-facilities/jpl/",
    category: "science",
    cadenceMinutes: 60,
  },
  {
    id: "nasa-kennedy",
    title: "NASA Kennedy Space Center",
    url: "https://www.nasa.gov/centers-and-facilities/kennedy/feed/",
    homepage: "https://www.nasa.gov/centers-and-facilities/kennedy/",
    category: "launch",
    cadenceMinutes: 60,
  },
  {
    id: "nasa-marshall",
    title: "NASA Marshall Space Flight Center",
    url: "https://www.nasa.gov/centers-and-facilities/marshall/feed/",
    homepage: "https://www.nasa.gov/centers-and-facilities/marshall/",
    category: "agency",
    cadenceMinutes: 60,
  },
  {
    id: "nasa-goddard",
    title: "NASA Goddard Space Flight Center",
    url: "https://www.nasa.gov/centers-and-facilities/goddard/feed/",
    homepage: "https://www.nasa.gov/centers-and-facilities/goddard/",
    category: "science",
    cadenceMinutes: 60,
  },
  {
    id: "nasa-wallops",
    title: "NASA Wallops Flight Facility",
    url: "https://www.nasa.gov/centers-and-facilities/wallops/feed/",
    homepage: "https://www.nasa.gov/centers-and-facilities/wallops/",
    category: "launch",
    cadenceMinutes: 60,
  },
  {
    id: "nasa-headquarters",
    title: "NASA Headquarters",
    url: "https://www.nasa.gov/centers-and-facilities/hq/feed/",
    homepage: "https://www.nasa.gov/centers-and-facilities/hq/",
    category: "agency",
    cadenceMinutes: 60,
  },
  {
    id: "nasa-ames",
    title: "NASA Ames Research Center",
    url: "https://www.nasa.gov/centers-and-facilities/ames/feed/",
    homepage: "https://www.nasa.gov/centers-and-facilities/ames/",
    category: "science",
    cadenceMinutes: 60,
  },
  {
    id: "nasa-armstrong",
    title: "NASA Armstrong Flight Research Center",
    url: "https://www.nasa.gov/centers-and-facilities/armstrong/feed/",
    homepage: "https://www.nasa.gov/centers-and-facilities/armstrong/",
    category: "science",
    cadenceMinutes: 60,
  },
  {
    id: "nasa-glenn",
    title: "NASA Glenn Research Center",
    url: "https://www.nasa.gov/centers-and-facilities/glenn/feed/",
    homepage: "https://www.nasa.gov/centers-and-facilities/glenn/",
    category: "science",
    cadenceMinutes: 60,
  },
  {
    id: "nasa-johnson",
    title: "NASA Johnson Space Center",
    url: "https://www.nasa.gov/centers-and-facilities/johnson/feed/",
    homepage: "https://www.nasa.gov/centers-and-facilities/johnson/",
    category: "agency",
    cadenceMinutes: 60,
  },
  {
    id: "esa-top-news",
    title: "ESA Top News",
    url: "https://www.esa.int/rssfeed/TopNews",
    homepage: "https://www.esa.int/",
    category: "agency",
    cadenceMinutes: 30,
  },
  {
    id: "space-news",
    title: "SpaceNews",
    url: "https://spacenews.com/feed/",
    homepage: "https://spacenews.com/",
    category: "industry",
    cadenceMinutes: 30,
  },
  {
    id: "spaceflight-now",
    title: "Spaceflight Now",
    url: "https://spaceflightnow.com/feed/",
    homepage: "https://spaceflightnow.com/",
    category: "launch",
    cadenceMinutes: 30,
  },
  {
    id: "space-dot-com",
    title: "Space.com",
    url: "https://www.space.com/feeds.xml",
    homepage: "https://www.space.com/",
    category: "industry",
    cadenceMinutes: 30,
  },
  {
    id: "universe-today",
    title: "Universe Today",
    url: "https://www.universetoday.com/feed/",
    homepage: "https://www.universetoday.com/",
    category: "astronomy",
    cadenceMinutes: 60,
  },
  {
    id: "planetary-society",
    title: "The Planetary Society",
    url: "https://www.planetary.org/rss/articles",
    homepage: "https://www.planetary.org/articles",
    category: "science",
    cadenceMinutes: 60,
  },
  {
    id: "space-policy-online",
    title: "SpacePolicyOnline",
    url: "https://spacepolicyonline.com/feed/",
    homepage: "https://spacepolicyonline.com/",
    category: "policy",
    cadenceMinutes: 30,
  },
  {
    id: "nasa-watch",
    title: "NASA Watch",
    url: "https://nasawatch.com/feed/",
    homepage: "https://nasawatch.com/",
    category: "policy",
    cadenceMinutes: 60,
  },
  {
    id: "phys-org-space",
    title: "Phys.org Space",
    url: "https://phys.org/rss-feed/space-news/",
    homepage: "https://phys.org/space-news/",
    category: "science",
    cadenceMinutes: 60,
  },
  {
    id: "science-daily-space-time",
    title: "ScienceDaily Space & Time",
    url: "https://www.sciencedaily.com/rss/space_time.xml",
    homepage: "https://www.sciencedaily.com/news/space_time/",
    category: "science",
    cadenceMinutes: 60,
  },
  {
    id: "earthsky",
    title: "EarthSky",
    url: "https://earthsky.org/feed/",
    homepage: "https://earthsky.org/",
    category: "astronomy",
    cadenceMinutes: 60,
  },
  {
    id: "astronomy-magazine",
    title: "Astronomy Magazine",
    url: "https://www.astronomy.com/feed/",
    homepage: "https://www.astronomy.com/",
    category: "astronomy",
    cadenceMinutes: 60,
  },
  {
    id: "astronomy-now",
    title: "Astronomy Now",
    url: "https://astronomynow.com/feed/",
    homepage: "https://astronomynow.com/",
    category: "astronomy",
    cadenceMinutes: 60,
  },
  {
    id: "spaceq",
    title: "SpaceQ",
    url: "https://spaceq.ca/feed/",
    homepage: "https://spaceq.ca/",
    category: "industry",
    cadenceMinutes: 60,
  },
  {
    id: "space-explored",
    title: "Space Explored",
    url: "https://spaceexplored.com/feed/",
    homepage: "https://spaceexplored.com/",
    category: "commercial",
    cadenceMinutes: 60,
  },
  {
    id: "satnews",
    title: "SatNews",
    url: "https://news.satnews.com/feed/",
    homepage: "https://news.satnews.com/",
    category: "satellite",
    cadenceMinutes: 60,
  },
  {
    id: "payload-space",
    title: "Payload Space",
    url: "https://payloadspace.com/feed/",
    homepage: "https://payloadspace.com/",
    category: "commercial",
    cadenceMinutes: 30,
  },
  {
    id: "european-spaceflight",
    title: "European Spaceflight",
    url: "https://europeanspaceflight.com/feed/",
    homepage: "https://europeanspaceflight.com/",
    category: "launch",
    cadenceMinutes: 60,
  },
  {
    id: "rocket-lab",
    title: "Rocket Lab",
    url: "https://www.rocketlabusa.com/updates/rss/",
    homepage: "https://www.rocketlabusa.com/updates/",
    category: "commercial",
    cadenceMinutes: 60,
  },
  {
    id: "redwire",
    title: "Redwire",
    url: "https://redwirespace.com/feed/",
    homepage: "https://redwirespace.com/newsroom/",
    category: "commercial",
    cadenceMinutes: 60,
  },
  {
    id: "firefly-aerospace",
    title: "Firefly Aerospace",
    url: "https://fireflyspace.com/feed/",
    homepage: "https://fireflyspace.com/news/",
    category: "commercial",
    cadenceMinutes: 60,
  },
  {
    id: "astrobotic",
    title: "Astrobotic",
    url: "https://www.astrobotic.com/feed/",
    homepage: "https://www.astrobotic.com/news/",
    category: "commercial",
    cadenceMinutes: 60,
  },
  {
    id: "sierra-space",
    title: "Sierra Space",
    url: "https://www.sierraspace.com/feed/",
    homepage: "https://www.sierraspace.com/newsroom/",
    category: "commercial",
    cadenceMinutes: 60,
  },
  {
    id: "us-space-force",
    title: "U.S. Space Force",
    url: "https://www.spaceforce.mil/DesktopModules/ArticleCS/RSS.ashx?ContentType=1&Site=1060&Category=9976&max=20",
    homepage: "https://www.spaceforce.mil/News/",
    category: "defense",
    cadenceMinutes: 60,
  },
  {
    id: "vandenberg-launches",
    title: "Vandenberg Space Force Base Launches",
    url: "https://www.vandenberg.spaceforce.mil/DesktopModules/ArticleCS/RSS.ashx?ContentType=1&Site=1028&Category=12341&max=20",
    homepage: "https://www.vandenberg.spaceforce.mil/News/Launches/",
    category: "launch",
    cadenceMinutes: 60,
  },
  {
    id: "noaa-space-weather",
    title: "NOAA Space Weather Prediction Center",
    url: "https://www.swpc.noaa.gov/rss.xml",
    homepage: "https://www.swpc.noaa.gov/",
    category: "science",
    cadenceMinutes: 30,
  },
  {
    id: "cnes",
    title: "CNES",
    url: "https://cnes.fr/en/rss.xml",
    homepage: "https://cnes.fr/en",
    category: "agency",
    cadenceMinutes: 60,
  },
  {
    id: "uk-space-agency",
    title: "UK Space Agency",
    url: "https://www.gov.uk/search/news-and-communications.atom?organisations%5B%5D=uk-space-agency",
    homepage: "https://www.gov.uk/government/organisations/uk-space-agency",
    category: "agency",
    cadenceMinutes: 60,
  },
  {
    id: "space-foundation",
    title: "Space Foundation",
    url: "https://www.spacefoundation.org/feed/",
    homepage: "https://www.spacefoundation.org/",
    category: "industry",
    cadenceMinutes: 60,
  },
  {
    id: "defense-news-space",
    title: "Defense News Space",
    url: "https://www.defensenews.com/arc/outboundfeeds/rss/category/space/?outputType=xml",
    homepage: "https://www.defensenews.com/space/",
    category: "defense",
    cadenceMinutes: 60,
  },
  {
    id: "c4isrnet-space",
    title: "C4ISRNET Space",
    url: "https://www.c4isrnet.com/arc/outboundfeeds/rss/category/battlefield-tech/space/?outputType=xml",
    homepage: "https://www.c4isrnet.com/battlefield-tech/space/",
    category: "defense",
    cadenceMinutes: 60,
  },
  {
    id: "aviation-week",
    title: "Aviation Week",
    url: "https://aviationweek.com/rss.xml",
    homepage: "https://aviationweek.com/space",
    category: "industry",
    cadenceMinutes: 60,
  },
  {
    id: "space-daily",
    title: "Space Daily",
    url: "https://www.spacedaily.com/spacedaily.xml",
    homepage: "https://www.spacedaily.com/",
    category: "industry",
    cadenceMinutes: 60,
  },
  {
    id: "mars-daily",
    title: "Mars Daily",
    url: "https://www.marsdaily.com/marsdaily.xml",
    homepage: "https://www.marsdaily.com/",
    category: "science",
    cadenceMinutes: 60,
  },
  {
    id: "space-ref",
    title: "SpaceRef",
    url: "https://spaceref.com/feed/",
    homepage: "https://spaceref.com/",
    category: "industry",
    cadenceMinutes: 60,
  },
];

export const NEWS_SOURCE_COUNT = NEWS_SOURCES.length;
