
export const X_SOURCES = [
  {
    id: "x-nasa",
    title: "NASA on X",
    username: "NASA",
    url: "https://x.com/NASA",
    homepage: "https://www.nasa.gov/",
    category: "agency",
    language: "en",
    region: "us",
    cadenceMinutes: 1440,
  },
  {
    id: "x-esa",
    title: "ESA on X",
    username: "esa",
    url: "https://x.com/esa",
    homepage: "https://www.esa.int/",
    category: "agency",
    language: "en",
    region: "europe",
    cadenceMinutes: 1440,
  },
  {
    id: "x-isro",
    title: "ISRO on X",
    username: "isro",
    url: "https://x.com/isro",
    homepage: "https://www.isro.gov.in/",
    category: "agency",
    language: "en",
    region: "india",
    cadenceMinutes: 1440,
  },
  {
    id: "x-jaxa-en",
    title: "JAXA on X",
    username: "JAXA_en",
    url: "https://x.com/JAXA_en",
    homepage: "https://global.jaxa.jp/",
    category: "agency",
    language: "en",
    region: "japan",
    cadenceMinutes: 1440,
  },
  {
    id: "x-cnsa-en",
    title: "CNSA on X",
    username: "CNSA_en",
    url: "https://x.com/CNSA_en",
    homepage: "https://www.cnsa.gov.cn/english/",
    category: "agency",
    language: "en",
    region: "china",
    cadenceMinutes: 1440,
  },
  {
    id: "x-cgtn-tech",
    title: "CGTN Tech on X",
    username: "CGTNTech",
    url: "https://x.com/CGTNTech",
    homepage: "https://www.cgtn.com/tech-sci",
    category: "science",
    language: "en",
    region: "china",
    cadenceMinutes: 1440,
  },
  {
    id: "x-mbrsc",
    title: "MBRSC on X",
    username: "MBRSpaceCentre",
    url: "https://x.com/MBRSpaceCentre",
    homepage: "https://www.mbrsc.ae/",
    category: "agency",
    language: "en",
    region: "mena",
    cadenceMinutes: 1440,
  },
  {
    id: "x-african-space-agency",
    title: "African Space Agency on X",
    username: "AfSA_AU",
    url: "https://x.com/AfSA_AU",
    homepage: "https://au.int/",
    category: "agency",
    language: "en",
    region: "africa",
    cadenceMinutes: 1440,
  },
  {
    id: "x-sansa",
    title: "SANSA on X",
    username: "SANSA7",
    url: "https://x.com/SANSA7",
    homepage: "https://www.sansa.org.za/",
    category: "agency",
    language: "en",
    region: "africa",
    cadenceMinutes: 1440,
  },
  {
    id: "x-polsa",
    title: "Polish Space Agency on X",
    username: "POLSA_GOV_PL",
    url: "https://x.com/POLSA_GOV_PL",
    homepage: "https://polsa.gov.pl/",
    category: "agency",
    language: "pl",
    region: "poland",
    cadenceMinutes: 1440,
  },
  {
    id: "x-brazilian-space-agency",
    title: "Brazilian Space Agency on X",
    username: "espacial_aeb",
    url: "https://x.com/espacial_aeb",
    homepage: "https://www.gov.br/aeb/",
    category: "agency",
    language: "pt",
    region: "brazil",
    cadenceMinutes: 1440,
  },
  {
    id: "x-israel-space-agency",
    title: "Israel Space Agency on X",
    username: "ILSpaceAgency",
    url: "https://x.com/ILSpaceAgency",
    homepage: "https://www.space.gov.il/en",
    category: "agency",
    language: "en",
    region: "israel",
    cadenceMinutes: 1440,
  },
  {
    id: "x-spacewatch-global",
    title: "SpaceWatch.Global on X",
    username: "SpaceWatchGL",
    url: "https://x.com/SpaceWatchGL",
    homepage: "https://spacewatch.global/",
    category: "industry",
    language: "en",
    region: "global",
    cadenceMinutes: 1440,
  },
  {
    id: "x-space-in-africa",
    title: "Space in Africa on X",
    username: "spaceinafrica1",
    url: "https://x.com/spaceinafrica1",
    homepage: "https://spaceinafrica.com/",
    category: "industry",
    language: "en",
    region: "africa",
    cadenceMinutes: 1440,
  },
  {
    id: "x-infoespacial",
    title: "InfoEspacial on X",
    username: "Infoespacial",
    url: "https://x.com/Infoespacial",
    homepage: "https://www.infoespacial.com/",
    category: "industry",
    language: "es",
    region: "spain",
    cadenceMinutes: 1440,
  },
  {
    id: "x-european-spaceflight",
    title: "European Spaceflight on X",
    username: "ESpaceflight",
    url: "https://x.com/ESpaceflight",
    homepage: "https://europeanspaceflight.com/",
    category: "launch",
    language: "en",
    region: "europe",
    cadenceMinutes: 1440,
  },
  {
    id: "x-space-news",
    title: "SpaceNews on X",
    username: "SpaceNews_Inc",
    url: "https://x.com/SpaceNews_Inc",
    homepage: "https://spacenews.com/",
    category: "industry",
    language: "en",
    region: "us",
    cadenceMinutes: 1440,
  },
  {
    id: "x-payload-space",
    title: "Payload on X",
    username: "payloadspace",
    url: "https://x.com/payloadspace",
    homepage: "https://payloadspace.com/",
    category: "commercial",
    language: "en",
    region: "us",
    cadenceMinutes: 1440,
  },
];

export const X_SOURCE_COUNT = X_SOURCES.length;
